### ISSUE TITLE
token left in shop

### ISSUE THREAD

**Issue by newbie029** [Realizedd/TokenManager#19]
sir can you add token left in shop please?
maybe in the GUI title.. or in the every shop item...
or make placeholder support for the shop GUI..

**Comment by Realizedd** [comment]
How the shops currently work is that every shop has a single inventory that can be viewed by multiple people, which means that there is no way to show the token left for each viewer. In order to implement it, I will have to create and hold on memory the shop inventories for every player online, and that is most likely to be too much stress on the server.
